### ISSUE TITLE
Change scripts['server'] to ['start']

### ISSUE THREAD

**Issue by featherplain** [feathericon/feathericon#108]
>npm WARN feathericon@1.0.0-beta.2 scripts['server'] should probably be scripts['start'].
>https://travis-ci.org/feathericon/feathericon/jobs/401389700#L2711

https://github.com/feathericon/feathericon/blob/aad3dec41b353ec09ca257b124e2aee80e1cecff/package.json#L14

**Comment by konojunya** [comment]
I'll create a Pull Request.
