### ISSUE TITLE
Which is right font size 14 px or 16 px ?

### ISSUE THREAD

**Issue by syokenz** [feathericon/feathericon#57]
Hi, I'm maintainer of [feathericon-rails](https://github.com/feathericon/feathericon-rails) and  [feathericon-sass](https://github.com/feathericon/feathericon-sass) . :octocat:
I'm trying upgrade to feathericon 0.7.0. :muscle:

I had checked the issue [Change font design size from 16px to 14px](https://github.com/feathericon/feathericon/issues/52) , but it looks difference between 
https://github.com/feathericon/feathericon/blob/v0.7.0/build/css/feathericon.css#L27
and
https://github.com/feathericon/feathericon/blob/v0.7.0/build/scss/_feathericon.scss#L31 .

The font size of _feathericon.scss is 14px, but feathericon.css is 16px.

Could you tell me which is right? :seedling:

**Comment by featherplain** [comment]
@syokenz 
Hi! thank you the report !
`14px` is correct, so https://github.com/feathericon/feathericon/blob/v0.7.0/build/css/feathericon.css#L27 is wrong font-size.

Bugfixed on https://github.com/feathericon/feathericon/pull/58 💪💪

**Comment by syokenz** [comment]
@featherplain Thanks !  🚀

**Comment by syokenz** [comment]
@featherplain  feathericon-rails and feathericon-sass v0.7.0 released ! 🎉   Thanks !
